base-application:
  image:
    repository: gcr.io/k8frastructure/logger
    tag: everything
    secret: image-pull
  host: nowak-dev.xyz
  ingress:
    enabled: true
    tls:
    - hosts:
      - nowak-dev.xyz
      secretName: dev-secret-infra-local-encrypt
    annotations:
      kubernetes.io/ingress.global-static-ip-name: nowak-dev-xyz-ip
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

global:
  certificate:
    secret: dev-secret-infra-local-encrypt
    environment: dev