replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: demo/logger
  tag: everything
#  secret: regcred
host: logger.loc
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
ingress:
  enabled: true