management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,health"
    health:
      show-details: always
  server:
    port: 8079

server:
  port: 8080

keycloak:
  enabled: true
  realm: nowak
  auth-server-url: "https://accounts.nowak-dev.xyz/auth"
  ssl-required: external
  resource: loggy
  securityConstraints:
    -
      authRoles:
        - member
      securityCollections:
        -
          name: member resource
          patterns:
            - /loggy/*
            - /owners/*
            - /trash/*