local-encrypt:
  enabled: true

local-networking:
  nginx-ingress:
    controller:
      service:
        loadBalancerIP: 34.68.187.183
        externalTrafficPolicy: Cluster

global:
  service:
    loadBalancerIP: 34.68.187.183
    externalTrafficPolicy: Cluster
  certificate:
    secret: dev-secret-infra-local-encrypt
    environment: dev
    domains:
      - nowak-dev.xyz
      - grafana.nowak-dev.xyz
      - kibana.nowak-dev.xyz
      - accounts.nowak-dev.xyz
      - openfaas.nowak-dev.xyz

local-elk:
  kibana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-dev
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        # auth
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        # message to display with an appropriate context why the authentication is required
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      path: /
      hosts:
        - kibana.nowak-dev.xyz
      tls:
        - secretName: dev-secret-infra-local-encrypt
          hosts:
            - kibana.nowak-dev.xyz

local-cloak:
  keycloak:
    keycloak:
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          certmanager.k8s.io/cluster-issuer: letsencrypt-dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        tls:
          - hosts:
              - accounts.nowak-dev.xyz
            secretName: dev-secret-infra-local-encrypt
        hosts:
        - accounts.nowak-dev.xyz
        path: /

local-functions:
  openfaas:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-dev
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        # auth
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        # message to display with an appropriate context why the authentication is required
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      tls:
      - hosts:
        - openfaas.nowak-dev.xyz
        secretName: dev-secret-infra-local-encrypt
      hosts:
        - host: openfaas.nowak-dev.xyz
          serviceName: gateway
          servicePort: 8080
          path: /

local-metrics:
  prometheus-operator:
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          certmanager.k8s.io/cluster-issuer: letsencrypt-dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - grafana.nowak-dev.xyz
        path: /
        tls:
          - secretName: dev-secret-infra-local-encrypt
            hosts:
            - grafana.nowak-dev.xyz
