local-elk:
  elasticsearch:
    replicas: 1
    minimumMasterNodes: 1
    antiAffinity: "soft"
    resources:
      requests:
        cpu: "100m"
        memory: "3Gi"
      limits:
        cpu: "1000m"
        memory: "3Gi"
  kibana:
    ingress:
      enabled: true
      annotations:
       kubernetes.io/ingress.class: nginx
      hosts:
        - kibana.nowak-dev.xyz

local-functions:
  openfaas:
    ingress:
      enabled: true
      hosts:
        - host: openfaas.nowak-dev.xyz

local-prometheus:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.nowak-dev.xyz

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 34.68.187.183
      externalTrafficPolicy: Cluster