global:
  certificate:
    secret: dev-secret-infra-local-encrypt
    environment: dev
    domains:
      - nowak-dev.xyz
      - grafana.nowak-dev.xyz
      - kibana.nowak-dev.xyz
      - opfaas.nowak-dev.xyz

local-elk:
  kibana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      tls:
      - hosts:
        - kibana.nowak-dev.xyz
        secretName: dev-secret-infra-local-encrypt
      hosts:
        - kibana.nowak-dev.xyz

local-functions:
  openfaas:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      tls:
      - hosts:
        - openfaas.nowak-dev.xyz
        secretName: dev-secret-infra-local-encrypt
      hosts:
        - host: openfaas.nowak-dev.xyz
          serviceName: gateway
          servicePort: 8080
          path: /

local-prometheus:
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      tls:
      - hosts:
        - grafana.nowak-dev.xyz
        secretName: dev-secret-infra-local-encrypt
      hosts:
        - grafana.nowak-dev.xyz


nginx-ingress:
  controller:
    service:
      loadBalancerIP: 34.68.187.183
      externalTrafficPolicy: Cluster