replicaCount: 1
image:
  pullPolicy: IfNotPresent
  requiresAuth: false
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  internalPortName: application
  metricsPort: 8079
  metricsPortName: metrics
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi
ingress:
  enabled: true