prometheus-operator:
  grafana:
    admin:
      existingSecret: basic-auth
      userKey: basic-auth-user
      passwordKey: basic-auth-password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-dev
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - metrics.nowak-dev.xyz
      path: /
      tls:
        - secretName: dev-secret-infra-local-encrypt
          hosts:
          - metrics.nowak-dev.xyz