prometheus-operator:
  grafana:
    admin:
      existingSecret: basic-auth
      userKey: basic-auth-user
      passwordKey: basic-auth-password
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - metrics.nowak-dev.loc
      path: /
    alertmanager:
      enabled: false
