keycloak:
  keycloak:
    username: admin
    existingSecret: basic-auth
    existingSecretKey: basic-auth-password
    keycloak:
      enabled: true
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          certmanager.k8s.io/cluster-issuer: letsencrypt-dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        tls:
          - hosts:
              - accounts.nowak-dev.xyz
            secretName: dev-secret-infra-local-encrypt
        hosts:
          - accounts.nowak-dev.xyz
        path: /