# here we configure the creation of our domains. These must be defined here before you creat the host in the ingress
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "secret-{{ template "fullname" . }}"
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: "{{ .Values.global.certificate.secret}}"
  dnsNames:
{{ toYaml .Values.global.certificate.domains | indent 2 }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
{{ toYaml .Values.global.certificate.domains | indent 6 }}
  issuerRef:
    name: "letsencrypt-{{ .Values.global.certificate.environment}}"
    kind: ClusterIssuer
