replicaCount: 1
image:
  pullPolicy: Always
  repository: alpine
  tag: latest
#  secret: regcred
service:
  name: java
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
ingress:
  enabled: false

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "100m"
      memory: "3Gi"
    limits:
      cpu: "1000m"
      memory: "3Gi"

kibana:
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    hosts:
      - kibana.loc

openfaas:
  functionNamespace: default
  ingress:
    enabled: true
    hosts:
      - host: openfaas.loc
        serviceName: gateway
        servicePort: 8080
        path: /
    annotations: {}
#      kubernetes.io/ingress.class: nginx